/**
 * Customer-facing RAPHA API-key management — EmmaTech-side abstraction.
 *
 * STATUS: NOT AVAILABLE in Phase 1 — by design, not by omission.
 *
 * WHY: RAPHA (control plane, repo RAPHA_v2) currently exposes NO trusted
 * service-level contract for managing a tenant's customer API keys. The audited
 * RAPHA service surface (X-Service-Token) is:
 *   POST   /api/v1/service/tenants
 *   PATCH  /api/v1/service/tenants/{tenant_id}/capabilities
 *   GET    /api/v1/service/tenants/{tenant_id}/capabilities
 *   POST   /api/v1/service/tenants/{tenant_id}/enrollment-tokens
 *   POST   /api/v1/service/tenants/{tenant_id}/enrollment-tokens/{token_id}/revoke
 * There is NO create/list/revoke for tenant *API keys* on the service surface.
 *
 * SECURITY DECISION: We do NOT invent or bypass RAPHA's security model. In
 * particular we NEVER mint or store raw RAPHA API keys inside the EmmaTech
 * database. Raw keys must be generated by RAPHA (which stores only their SHA-256
 * hash) and shown to the customer exactly once by RAPHA's own response.
 *
 * REQUIRED RAPHA SERVICE CONTRACT (to be implemented in a RAPHA phase before
 * EmmaTech can enable this feature) — documented here so the dependency is
 * explicit:
 *
 *   GET    /api/v1/service/tenants/{tenant_id}/api-keys
 *          -> [{ key_id, name, prefix, created_at, last_used_at, status }]  (metadata only; NEVER the raw key or hash)
 *   POST   /api/v1/service/tenants/{tenant_id}/api-keys   { name }
 *          -> { key_id, name, api_key }   (raw api_key returned ONCE; RAPHA stores only its hash)
 *   POST   /api/v1/service/tenants/{tenant_id}/api-keys/{key_id}/revoke
 *          -> { key_id, status: "revoked" }
 *   Auth: X-Service-Token (server-side only). Tenant resolved server-side.
 *
 * This module provides the stable EmmaTech interface + availability gate so the
 * portal and the eventual RAPHA client method can be wired without a rewrite.
 */
import type { AppConfig } from './config.js';

/** Metadata for a customer API key (never the raw key or its hash). */
export interface ApiKeyMetadata {
  key_id: string;
  name: string;
  /** Short non-secret prefix for identification (e.g. "rak_ab12"). */
  prefix: string;
  created_at: string;
  last_used_at: string | null;
  status: 'active' | 'revoked';
}

/** Raw-key result — returned to the customer exactly once, never persisted. */
export interface ApiKeyCreated {
  key_id: string;
  name: string;
  /** Raw secret; shown once by RAPHA, never stored by EmmaTech. */
  api_key: string;
}

/**
 * Whether customer API-key management can be served. It requires BOTH a
 * configured RAPHA service AND the (not-yet-implemented) RAPHA service-level
 * API-key contract. The capability flag stays false until RAPHA ships it.
 */
export function apiKeysAvailable(cfg: AppConfig): boolean {
  // Availability requires BOTH a configured RAPHA service AND the (not-yet-
  // implemented) RAPHA service-level API-key contract above. The contract flag
  // stays false until RAPHA ships it, so this is currently always false.
  const raphaConfigured = Boolean(cfg.raphaBaseUrl && cfg.raphaServiceToken);
  const RAPHA_APIKEY_CONTRACT_AVAILABLE = false;
  return raphaConfigured && RAPHA_APIKEY_CONTRACT_AVAILABLE;
}

/** Human-facing reason surfaced by the endpoint/UI while gated off. */
export const API_KEYS_UNAVAILABLE_REASON =
  'Customer API-key management is not yet available. It will be enabled once the RAPHA control plane exposes a service-level API-key contract.';
